In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os
folder_path = '/content/drive/MyDrive'
for file in os.listdir(folder_path):
    print(file)

Colab Notebooks
ecommerce_dataset
UpliftJEE CRM.gsheet
food_delivery_data.csv
food_delivery_cleaned.csv

In [4]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/food_delivery_data.csv')

In [5]:
df.shape

(1508, 21)

In [6]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(' ', '_')
)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1508 entries, 0 to 1507
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             1508 non-null   object
 1   order_date           1508 non-null   object
 2   order_time           1508 non-null   object
 3   customer_id          1508 non-null   object
 4   area                 1508 non-null   object
 5   food_item            1508 non-null   object
 6   quantity             1508 non-null   int64
 7   unit_price           1508 non-null   int64
 8   item_total           1508 non-null   int64
 9   distance_km          1508 non-null   float64
 10  coupon_code          1508 non-null   object
 11  discount_amount      1508 non-null   int64
 12  delivery_fee         1508 non-null   int64
 13  final_amount         1508 non-null   int64
 14  delivery_time_min    1508 non-null   int64
 15  order_type           1508 non-null   object
 16  payment_method       1478 non-null   object
 17  delivery_partner_id  1508 non-null   object
 18  is_refunded          1508 non-null   bool
 19  refund_reason        163 non-null    object
 20  rating               1433 non-null   float64
dtypes: bool(1), float64(2), int64(7), object(11)
memory usage: 237.2+ KB

In [8]:
df['order_date'] = df['order_date'].apply(pd.to_datetime)

In [9]:
df.head()

,order_id,order_date,order_time,customer_id,area,food_item,quantity,unit_price,item_total,distance_km,...,discount_amount,delivery_fee,final_amount,delivery_time_min,order_type,payment_method,delivery_partner_id,is_refunded,refund_reason,rating
0,ORD00001,2025-03-24,21:25,CUST0124,Hazratganj,Burger,2,150,300,1.6,...,0,0,300,17,Regular,Wallet,DP005,False,NaN,3.6
1,ORD00002,2025-05-25,07:14,CUST0061,Vikas Nagar,PIZZA,2,350,700,5.1,...,0,41,741,32,Regular,Card,DP035,False,NaN,3.9
2,ORD00003,2025-06-24,08:37,CUST0239,Vikas Nagar,Ice Cream,1,130,130,1.6,...,0,0,130,19,Regular,Wallet,DP021,False,NaN,3.6
3,ORD00004,2025-03-18,10:11,CUST0215,ALAMBAGH,Burger,2,150,300,6.5,...,0,52,352,45,Bulk,UPI,DP033,False,NaN,1.9
4,ORD00005,2025-05-06,12:42,CUST0048,Gomti Nagar,PARATHA,2,70,140,9.6,...,0,77,217,52,Regular,Wallet,DP005,False,NaN,2.2

In [10]:
df[(df['is_refunded'] == True) & (df['refund_reason'].isna())].shape[0]

0

no order is refunded without giving the reason so all refund reason and rating are structural null but payment method is real null

In [11]:
print(df.isnull().sum())

order_id                  0
order_date                0
order_time                0
customer_id               0
area                      0
food_item                 0
quantity                  0
unit_price                0
item_total                0
distance_km               0
coupon_code               0
discount_amount           0
delivery_fee              0
final_amount              0
delivery_time_min         0
order_type                0
payment_method           30
delivery_partner_id       0
is_refunded               0
refund_reason          1345
rating                   75
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(7)

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
df['distance_km'].describe()

count    1501.000000
mean        6.205530
std         3.410441
min        -8.300000
25%         3.300000
50%         6.300000
75%         9.200000
max        12.000000
Name: distance_km, dtype: float64

In [15]:
df['payment_method'] = df['payment_method'].str.replace('null', 'unknown', case=False)

In [16]:
df['area'].unique()

array(['Hazratganj', ' Vikas Nagar ', 'Vikas Nagar', 'ALAMBAGH',
       'Gomti Nagar', 'Aliganj', 'Indira Nagar', 'CHINHAT', 'Alambagh',
       'AMINABAD', 'Chinhat', 'aminabad', 'Rajajipuram', 'GOMTI NAGAR',
       'Mahanagar', ' Mahanagar ', ' Gomti Nagar ', ' Alambagh ',
       'INDIRA NAGAR', 'vikas nagar', 'Aminabad', 'hazratganj',
       ' Aliganj ', 'HAZRATGANJ', 'MAHANAGAR', 'RAJAJIPURAM', 'mahanagar',
       'VIKAS NAGAR', 'ALIGANJ', ' Aminabad ', 'rajajipuram',
       ' Indira Nagar ', ' Chinhat ', 'alambagh', ' Hazratganj ',
       'gomti nagar', 'indira nagar', ' Rajajipuram ', 'chinhat',
       'aliganj'], dtype=object)

In [17]:
df['area'] = (
      df['area']
      .str.strip()
      .str.lower()
      .str.replace(' ', '')
)

In [18]:
df['area'].unique()

array(['hazratganj', 'vikasnagar', 'alambagh', 'gomtinagar', 'aliganj',
       'indiranagar', 'chinhat', 'aminabad', 'rajajipuram', 'mahanagar'],
      dtype=object)

In [19]:
df['food_item'] = (
      df['food_item']
      .str.strip()
      .str.lower()
      .str.replace(' ', '')
)

In [20]:
df['food_item'].unique()

array(['burger', 'pizza', 'icecream', 'paratha', 'thali', 'cake',
       'noodles', 'momos', 'shake', 'sandwich', 'biryani', 'salad',
       'pasta', 'rolls', 'dosa'], dtype=object)

In [21]:
df.to_csv('food_delivery_cleaned.csv', index=False)

In [22]:
df.to_csv('/content/drive/MyDrive/food_delivery_cleaned.csv', index=False)